from enum import Enum


class DocumentType(str, Enum):
    CEDULA = "CEDULA"
    PASAPORTE = "PASAPORTE"
    CARNET = "CARNET"
    LICENCIA = "LICENCIA"
    RESIDENCIA = "RESIDENCIA"
    OTRO = "OTRO"


class ResultOutcome(str, Enum):
    CORRECTO = "CORRECTO"
    REVISION = "REVISIÓN"
    INCIDENCIA = "INCIDENCIA"
    NO_VERIFICABLE = "NO_VERIFICABLE"


class Severity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RuleCode(str, Enum):
    CEDULA_NO_LEGIBLE = "CEDULA_NO_LEGIBLE"
    DIGITO_CONTROL_NO_COINCIDE = "DIGITO_CONTROL_NO_COINCIDE"
    CEDULA_DUPLICADA = "CEDULA_DUPLICADA"
    CEDULA_FALTANTE = "CEDULA_FALTANTE"
    CEDULA_EXCEDENTE = "CEDULA_EXCEDENTE"
    NUMERO_DOCUMENTO_NO_COINCIDE = "NUMERO_DOCUMENTO_NO_COINCIDE"
    ASOCIACION_PENDIENTE = "ASOCIACION_PENDIENTE"
    VERIFICACION_MANUAL_COMPLETA = "VERIFICACION_MANUAL_COMPLETA"
    NOMBRE_NO_COINCIDE = "NOMBRE_NO_COINCIDE"
    SEGUNDO_NOMBRE_FALTANTE = "SEGUNDO_NOMBRE_FALTANTE"
    APELLIDOS_INVERTIDOS = "APELLIDOS_INVERTIDOS"
    APELLIDO_CASADA = "APELLIDO_CASADA"
    DIFERENCIA_APELLIDO = "DIFERENCIA_APELLIDO"
    DOCUMENTO_EXTRANJERO_NO_PASAPORTE = "DOCUMENTO_EXTRANJERO_NO_PASAPORTE"
    DOCUMENTO_NO_ASOCIADO = "DOCUMENTO_NO_ASOCIADO"
    DIFERENCIA_DETECTADA = "DIFERENCIA_DETECTADA"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
